Animacja zaciemniania tła przy otwarciu edycji opisu karty (i animacja odwrotna przy wyłączaniu edycji opisu)
emkarcinos/WMIAdventure pull request #403
Opened 2021-07-22 09:38 UTC by Michael-Czekanski

Close #357

2021-07-23 10:48 UTC, mattyl006 requested changes
Spoko to jest jak dla mnie, tylko dodaj jeszcze do pozostałych Popupów

2021-07-23 14:08 UTC, Michael-Czekanski commented
Dodałem animacje chyba już do wszystkich popupów. @mattyl006 a te zmiany w pliku `yarn.lock` nic nie popsują?

2021-07-23 16:09 UTC, mattyl006 commented
> Dodałem animacje chyba już do wszystkich popupów. @mattyl006 a te zmiany w pliku `yarn.lock` nic nie popsują?

Raczej nie, odpalałem to u siebie i było git

2021-07-23 16:09 UTC, mattyl006 approved these changes

2021-07-24 08:57 UTC, Michael-Czekanski commented
A już wiem czemu takie zmiany w yarn.lock były, bo ja zamiast `npm` miałem `yarn` jako package manager

2021-07-24 09:34 UTC, Michael-Czekanski commented
Jakby ktoś mógł jeszcze sprawdzić, czy animacja przy wybieraniu karty do edycji jest ok

2021-07-24 11:10 UTC, mattyl006 commented
> A już wiem czemu takie zmiany w yarn.lock były, bo ja zamiast `npm` miałem `yarn` jako package manager

No to dlatego

2021-07-24 19:25 UTC, emkarcinos commented
Wszystko wydaje się być git. Rozwiąż konflikt i można mergować.

2021-07-24 19:25 UTC, emkarcinos requested changes
Rozwiąż konflikt

2021-07-24 20:51 UTC, Michael-Czekanski commented
@emkarcinos konflikt rozwiązany, nie mogę mergować dopóki jest *Changes requested*

2021-07-24 21:00 UTC, emkarcinos approved these changes

2021-07-24 21:00 UTC, merged