New Card Send Popup
emkarcinos/WMIAdventure pull request #416
Opened 2021-07-24 00:51 UTC by Michael-Czekanski

Tak narazie wygląda popup wysłania karty, narazie zrobiłem tylko pierwszą część:
![obraz](https://user-images.githubusercontent.com/43492764/126852797-9e453931-a1d0-46dc-b201-663abddad5d5.png)

Mobilka:
![obraz](https://user-images.githubusercontent.com/43492764/126852812-0f46446d-6c1e-4175-b120-7a2af211190c.png)

Close #371

2021-07-24 00:54 UTC, Michael-Czekanski commented
@emkarcinos zastanawiam się, czy ten label nad polem tekstowym jest potrzebny, skoro mamy podpowiedź `Wiadomość` wewnątrz pola tekstowego

![obraz](https://user-images.githubusercontent.com/43492764/126852890-2ac45b22-3e0e-4ebf-82bd-d52b9d01fa1e.png)

2021-07-24 06:10 UTC, emkarcinos commented
Faktycznie, możesz to wyrzucić

2021-07-24 12:13 UTC, mattyl006 commented
> @emkarcinos zastanawiam się, czy ten label nad polem tekstowym jest potrzebny, skoro mamy podpowiedź `Wiadomość` wewnątrz pola tekstowego
> 
> ![obraz](https://user-images.githubusercontent.com/43492764/126852890-2ac45b22-3e0e-4ebf-82bd-d52b9d01fa1e.png)

Według dobrych praktych html, label zawsze powinien być.

2021-07-24 12:18 UTC, mattyl006 requested changes

2021-07-24 12:18 UTC, mattyl006 commented on WMIAdventure/frontend/src/js/pages/creative/CardsCreator/atoms/SendCardPopup/SendCardPopup.js
> +                                <TextAreaLabel>Wiadomość</TextAreaLabel>
Label powinien posiadać atrybut htmlFor=id_takie_jak_input, aby był bezpośrednio związany z tym inputem, to też sprawi że jak klikniemy w ten label to aktywuje się przypisany do niego input

2021-07-25 18:30 UTC, Michael-Czekanski commented
Popup chyba skończony, dodałem `additionalComments` do requesta przy wysyłaniu karty.

![image](https://user-images.githubusercontent.com/43492764/126909331-b25eb0d4-c88a-47f0-a65d-a28dad066d66.png)

![image](https://user-images.githubusercontent.com/43492764/126909358-5a94628b-bffd-4ba9-9d7a-5768ecc9426a.png)

![image](https://user-images.githubusercontent.com/43492764/126909319-9c6e7db4-c058-4b5d-9328-34d9dbcfddb5.png)

@mattyl006 jak będziesz mógł to rzuć okiem, czy dobrze style zrobiłem

---

@emkarcinos narazie odpowiedź od serwera jest dość surowa, ale tak czy siak zdecydowałem się ją już teraz zawrzeć. Mogę nie mergować tego pull'a dopóki nie ogarniemy taska z przyjazną odpowiedzią od serwera, dlaczego karta nie została przyjęta.

Przykład surowej odpowiedzi:

![image](https://user-images.githubusercontent.com/43492764/126909485-a40e7b44-7878-45b9-93a0-ef494173e15d.png)

2021-07-25 18:54 UTC, Michael-Czekanski commented
W sumie mamy task #354, czyli to po stronie frontendu powinno być przetwarzanie surowej odpowiedzi od backendu na przyjazną dla użytkownika? @emkarcinos

2021-07-25 19:15 UTC, emkarcinos commented
@Michael-Czekanski
Myślałem żeby właśnie na backendzie to ładnie zrobić.

2021-07-25 19:31 UTC, emkarcinos commented
Ten texbox w screenshocie jest kwadratowy? 
W designie były lekko zaokrąglone rogi, jeżeli tego nie ma to warto to jeszcze dodać

2021-07-25 20:09 UTC, Michael-Czekanski commented
A racja, dodam to jeszcze

2021-07-25 20:51 UTC, Michael-Czekanski commented
> 
> 
> Ten texbox w screenshocie jest kwadratowy?
> W designie były lekko zaokrąglone rogi, jeżeli tego nie ma to warto to jeszcze dodać


![image](https://user-images.githubusercontent.com/43492764/126913095-407a10a1-92ce-471b-b1d2-a98ae915a7b2.png)

2021-07-25 21:09 UTC, emkarcinos approved these changes
Teraz jest ładnie.
Nie wiem jak z kodem, bo się nie znam

2021-08-01 20:46 UTC, mattyl006 approved these changes
Gites style

2021-08-03 17:05 UTC, emkarcinos commented
Czy ktoś jeszcze pracuje nad tym pullem? Od tygodnia nie było żadnych prac, @mattyl006 zatwierdził zmiany. Mergujemy?

2021-08-03 17:07 UTC, emkarcinos commented
@Michael-Czekanski Dopiero teraz zobaczyłem, że nazwałeś pole w jsonie `additionalComments`, ja robiąc taska #412 zapomniałem się tym zasugerować i nazwałem to pole `comment`

2021-08-03 17:08 UTC, emkarcinos requested changes

2021-08-03 17:08 UTC, emkarcinos commented on WMIAdventure/frontend/src/js/pages/creative/CardsCreator/CardsCreator.js
> +        additionalComments: "",
Na backendzie jest `comment`

2021-08-03 17:10 UTC, emkarcinos reviewed
Trzeba zmergować brancha [CardEditor_Comments](https://github.com/emkarcinos/WMIAdventure/tree/CardEditor_Comments)

2021-08-04 12:30 UTC, Michael-Czekanski commented on WMIAdventure/frontend/src/js/pages/creative/CardsCreator/CardsCreator.js
> +        additionalComments: "",
Zrobione

2021-08-04 12:31 UTC, Michael-Czekanski commented
> 
> 
> Trzeba zmergować brancha [CardEditor_Comments](https://github.com/emkarcinos/WMIAdventure/tree/CardEditor_Comments)

Zmergowane



> 
> 
> Gites style, tylko w sumie te **font-family** niepotrzebne chyba, bo globalnie w _index.css_ jest

Racja, wywaliłem to

2021-08-04 13:21 UTC, emkarcinos approved these changes

2021-08-04 13:21 UTC, merged