Card editor frontend image upload
emkarcinos/WMIAdventure pull request #441
Opened 2021-08-07 10:12 UTC by Michael-Czekanski

Dodałem uploadowanie obrazka/ikony karty, można potestować. 

Jeszcze nie wiem jak z wyświetlaniem aktualnego obrazka danej kart przy jej edycji, bo nie działa akceptowanie karty, która ma obrazek (zrobiłem issue #439)

Closes #375

2021-08-08 07:52 UTC, emkarcinos commented
Co się stało w tym pull requeście? Dużo jakiś commitów w ogóle nie związanych z tym pullem, coś nie tak przy mergowaniu poszło?

2021-08-08 07:53 UTC, emkarcinos requested changes
"Wybierz z pliku" powinien być wyśrodkowany względem obrazka:

![image](https://user-images.githubusercontent.com/11946540/128625008-44de4dd5-ba8a-4144-8b55-760f78a137e0.png)
![image](https://user-images.githubusercontent.com/11946540/128625018-276c15ff-db3e-49ba-8f32-30f92778fbe5.png)

2021-08-08 08:07 UTC, emkarcinos commented
Ten obrazek który tam jest mógłby się wyświetlać w normalnych proporcjach, tylko po prostu zmniejszony.
![image](https://user-images.githubusercontent.com/11946540/128625411-0071f959-e118-4322-b8f9-e6e321c5d531.png)
Tutaj dodałem prostokątny obrazek i się rozjechał, a lepiej moim zdaniem byłoby zrobić to w taki sposób, żeby się dopasował do tego boxa.

W figmie ta opcja nazywa się `fit`
![image](https://user-images.githubusercontent.com/11946540/128625455-c101415b-fa34-4b24-93cb-85138973985a.png)

2021-08-08 10:29 UTC, mattyl006 commented
> Ten obrazek który tam jest mógłby się wyświetlać w normalnych proporcjach, tylko po prostu zmniejszony.
> ![image](https://user-images.githubusercontent.com/11946540/128625411-0071f959-e118-4322-b8f9-e6e321c5d531.png)
> Tutaj dodałem prostokątny obrazek i się rozjechał, a lepiej moim zdaniem byłoby zrobić to w taki sposób, żeby się dopasował do tego boxa.
> 
> W figmie ta opcja nazywa się `fit`
> ![image](https://user-images.githubusercontent.com/11946540/128625455-c101415b-fa34-4b24-93cb-85138973985a.png)

A w css, trzeba pobawić się z `object-fit:`, w tym przypadku chyba `object-fit: contain` albo `object-fit: cover`.

2021-08-08 14:26 UTC, Michael-Czekanski commented
> 
> 
> Co się stało w tym pull requeście? Dużo jakiś commitów w ogóle nie związanych z tym pullem, coś nie tak przy mergowaniu poszło?

W sumie bez żadnych problemów, zmergowałem z mainem. Pewnie powinienem był najpierw zmergować maina na branchu CardEditor_CardImage

2021-08-08 15:17 UTC, Michael-Czekanski commented
@emkarcinos już naprawiłem ten obrazek i wyśrodkowałem "Załaduj z pliku"

2021-08-09 17:27 UTC, emkarcinos approved these changes

2021-08-10 06:21 UTC, mattyl006 approved these changes

2021-08-10 14:09 UTC, merged