Battle outcome with cards
emkarcinos/WMIAdventure pull request #644
Opened 2021-11-07 14:42 UTC by emkarcinos

Closes #621 
Closes #622

2021-11-07 17:17 UTC, mattyl006 commented
Jakiś test django nie przeszedł

2021-11-07 19:52 UTC, emkarcinos commented
Poprawione

2021-11-07 22:47 UTC, mattyl006 requested changes
Nie pojawiają się u mnie te karty, są nulle i nie wiem dlaczego.
Sprawdzałem czy na pewno dobry branch, i czy pull aktualny i czy migrate.

![image](https://user-images.githubusercontent.com/51495505/140664698-95d49ca4-6ed1-49b2-875e-749730be9f8f.png)
![image](https://user-images.githubusercontent.com/51495505/140664744-fdae886b-75ad-48bf-b1ed-b7523fd9b9ee.png)

2021-11-08 08:22 UTC, emkarcinos commented
Wydaje mi się, że Twoje karty nie mają obrazków - widzę że przy Profilu są karty bez obrazków z samymi tytułami. Dodaj w edytorze ikony i zobacz jeszcze raz

2021-11-08 15:37 UTC, mattyl006 requested changes
To zamiast tych znaków zapytania, powinien być ten dark placeholder w takim przypadku, gdy są widoczne ale nie ma ikony

2021-11-08 16:51 UTC, mattyl006 requested changes
W mobile nie wyświetlają się ikonki po szybkiej walce

2021-11-08 16:51 UTC, mattyl006 commented on WMIAdventure/frontend/src/js/components/battle/organisms/OpponentSelected/OpponentSelected.js
>                                      setOpacity={this.state.postBattleOpacity}
Jeszcze w mobile trzeba te propsy dodać

2021-11-08 17:08 UTC, mattyl006 commented
Jeszcze konflikty z mainem

2021-11-08 17:17 UTC, emkarcinos commented
Domergowałem

2021-11-08 17:58 UTC, mattyl006 approved these changes

2021-11-08 17:59 UTC, merged