Card Editor lag fix
emkarcinos/WMIAdventure pull request #653
Opened 2021-11-08 17:39 UTC by emkarcinos

Fixes #646

Nie naprawiłem case gdy mamy w karcie dwa takie same efekty.

2021-11-09 07:44 UTC, mattyl006 requested changes
Teraz u Ciebie nie ma tego problemu?
Bo mi nadal przy edycji laguje, najbardziej jak się nowy efekt chce wybrać z listy.
I to tylko przy edycji, w tworzeniu nowej jest wszystko ok, tak jakby coś było nie tak w 
case'ach gdzie już jakieś początkowe dane do karty mamy bo ją wczytujemy

2021-11-09 21:58 UTC, Michal-Czekanski requested changes
hm, u mnie też edycja karty jest praktycznie niemożliwa, dodawanie efektów nie działa, a dodanie levela laguje

2021-11-10 09:19 UTC, mattyl006 commented
> hm, u mnie też edycja karty jest praktycznie niemożliwa, dodawanie efektów nie działa, a dodanie levela laguje
> 
> update: jednak dodanie efektu jest możliwe, tylko jest niewidzialna lista efektów, która nawet po niechcianym dodaniu jakiegoś efektu (bo nie widzimy tej listy, a przez przypadek na nią klikamy) nie zamyka się

U mnie takk samo

2021-11-10 12:10 UTC, emkarcinos commented
U mnie tak samo, faktycznie nie sprawdziłem przy edycji

2021-11-10 13:15 UTC, mattyl006 commented
> U mnie tak samo, faktycznie nie sprawdziłem przy edycji

Ogólnie to cały task dotyczy tylko edycji

2021-11-12 15:49 UTC, mattyl006 approved these changes
Działa!

2021-11-12 16:51 UTC, merged