Battle integration
emkarcinos/WMIAdventure pull request #666
Opened 2021-11-17 18:18 UTC by emkarcinos

2021-11-20 22:51 UTC, Michal-Czekanski commented
Randomizacja decka ma problemy u mnie:
- deck przed zadziałaniem randomizacji
![image](https://user-images.githubusercontent.com/43492764/142743052-3ec8db65-9a8f-4390-a103-5e68320c1860.png)
- po
![image](https://user-images.githubusercontent.com/43492764/142743060-26b300eb-fef5-4a81-bd6c-0faf61973aa5.png)

Jedynka zniknęła, trójka jest zduplikowana

2021-11-21 09:53 UTC, mattyl006 commented
@Michal-Czekanski z tego co ja kodziłem, tam gdzie jest kompaktowy widok, to jest pięć tak naprawdę kompaktowych widoków, i ten co ma order=1 jest widoczny, reszta ukryta. Wygląda na to że z tymi atrybutami order jest coś nie tak w MiniCardach, zbadaj jak one się zmieniają w zależności od tej tablicy, to może znajdziesz wtedy błąd

2021-11-21 12:30 UTC, mattyl006 requested changes
Potestowałem u mnie i nie zgadza się często FullCardView z wysuwaną kartą CompactCardView.

Np. Tutaj się wysunęła z dołu "Przykład 4" full view
![image](https://user-images.githubusercontent.com/51495505/142761630-67449a70-5985-451d-be02-022c30ff5f61.png)

A do przodu wysunęła CompactView "Przykład 5"
![image](https://user-images.githubusercontent.com/51495505/142761683-1d3c8b30-d4d2-45dd-bb1a-ff5b2e791fe5.png)

Właściwie to w Compactowych zawsze jest "Przykład 1" i "Przykład 5", podejrzewam że to przez style. Nie te karty co trzeba mają display przyrywające pozostałe, po pierwszej turze. Tak właściwie to co piąta tura jest ok, w pozostałych przypadkach złe karty kompaktowe przykrywają pozostałe.

To w Div, componentu CompactCardView, może to przez to i trzeba tu jakoś poprawić te obsłużenie, którą kartę ma pokazywać.
![image](https://user-images.githubusercontent.com/51495505/142761905-4b749113-7646-43d9-8834-e007bf39672b.png)

2021-11-21 12:35 UTC, mattyl006 commented
Mam jeszcze sugestię, aby ten update kolejności nie wykonywał się równocześnie z kolejną kartą FullView wysuwaną. Tylko najpierw update tej kolejności, a później kolejna karta usera lub enemy. Tak to będzie lepiej wyglądało moim zdaniem, i będzie bardziej wiadomo o co chodzi.

2021-11-21 14:30 UTC, mattyl006 approved these changes
Teraz zajebiście, tylko jeszcze bym w tym ładowaniu, zmienił napis z "Szybka walka" na "Wizualizacja walki" czy coś w tym stylu

2021-11-21 16:52 UTC, Michal-Czekanski commented on WMIAdventure/backend/WMIAdventure_backend/battle/businesslogic/Calculator.py
> +        return int(power + uniform(-1, 1) * power_range)
bezpieczniej by było wszędzie zrobić najpierw `round`, a potem na inta konwertować

2021-11-21 17:47 UTC, Michal-Czekanski requested changes
Nice! Drobne rzeczy zauważyłem, zostawiłem odniesienia w komentarzach

2021-11-21 17:47 UTC, Michal-Czekanski commented on WMIAdventure/frontend/src/js/api/data-models/battle/Deck.js
> +    }
na backendzie to inaczej działa, karta ma updatowane rzeczy typu turns stopped i aktywność buffów tylko przy użyciu danej karty - tutaj powinno być wykonywane `onTurnEnd` tylko na użytej karcie

2021-11-21 17:47 UTC, Michal-Czekanski commented on WMIAdventure/frontend/src/js/api/gateways/BattleAPIGateway.js
> +
ten kodzik jeszcze potrzebny?

2021-11-21 17:47 UTC, Michal-Czekanski commented on WMIAdventure/frontend/src/js/components/battle/organisms/BattleView/BattleView.js
>      }
Jeśli Ci się chciało to chyba można zrobić osobną funkcje, co zwraca odpoweidni obiekt na podstawie levela np. `{ common: true, gold: false, epic: false}` no i potem zrobić jeden tylko `FullCardView`  zamiast trzech i mu tam podawać te wyliczone booleany

2021-11-21 17:50 UTC, Michal-Czekanski commented on WMIAdventure/frontend/src/js/api/data-models/battle/Deck.js
> +    }
jeśli dobrze pamiętam, to chodziło nam o to, że jak zbufujemy następną kartę, a potem zrobimy randomizację decka, to żeby ten buffik dalej był i czekał sobie na wykonanie tej karty, jak przyjdzie znowu na nią kolej

2021-11-28 21:07 UTC, Michal-Czekanski commented
Brakuje jeszcze takiej linijki w `Battle.nextTurn()`
![image](https://user-images.githubusercontent.com/43492764/143785975-69d2ca0a-94d2-4ef2-a84e-62dfc26823ba.png)

2021-11-28 21:21 UTC, emkarcinos commented
> Brakuje jeszcze takiej linijki w `Battle.nextTurn()` ![image](https://user-images.githubusercontent.com/43492764/143785975-69d2ca0a-94d2-4ef2-a84e-62dfc26823ba.png)

Czemu miałbym to tam dodawać? W `Turn` to wywołujemy jak skończą się efekty do wykonania

2021-11-28 21:42 UTC, Michal-Czekanski approved these changes

2021-11-28 21:42 UTC, merged