Design przebiegu walki na desktop
emkarcinos/WMIAdventure pull request #678
Opened 2021-11-21 19:23 UTC by mattyl006

closes #647

2021-11-26 16:35 UTC, emkarcinos commented on WMIAdventure/frontend/src/js/components/battle/organisms/BattleView/BattleView.js
> +        console.log(userTurn);
Zostało Ci po debugowaniu :P

2021-11-26 16:37 UTC, emkarcinos commented on WMIAdventure/frontend/src/js/components/battle/organisms/BattleView/BattleView.js
> +        }, nextStepAnimationDuration);
`this.setState({
    compactCardOnTopScale: {user: userTurn, enemy: !userTurn, middle: '1'}
`

2021-11-26 16:40 UTC, mattyl006 commented on WMIAdventure/frontend/src/js/components/battle/organisms/BattleView/BattleView.js
> +        console.log(userTurn);
outdated, w kolejnych commitach tego nie ma już

2021-11-27 14:15 UTC, emkarcinos approved these changes

2021-11-28 00:02 UTC, Michal-Czekanski requested changes
Animacje zadymiste, płynne, bardzo ładnie to wygląda

Przetestowałem u siebie na firefox i dziwne rzeczy się dzieją, używane karty się nie zgadzają
![2021-11-28_00-50-35](https://user-images.githubusercontent.com/43492764/143723909-41306d48-b2d1-4389-be85-66661f40d874.gif)

2021-11-28 14:12 UTC, Michal-Czekanski approved these changes

2021-11-28 21:48 UTC, merged