Damage effect
emkarcinos/WMIAdventure pull request #682
Opened 2021-11-28 14:10 UTC by mattyl006

closes #672

2021-11-28 14:44 UTC, Michal-Czekanski requested changes
Wizualizacja dmg ładna, ale sam sposób trzeba poprawić

2021-11-28 14:44 UTC, Michal-Czekanski commented on WMIAdventure/frontend/src/js/components/battle/organisms/BattleView/BattleView.js
> +
Taki sposób nie działa: mam np. efekt zadawanie dmg jako ostatni, jako pierwszy efekto randomizacji decka. Przy pierwszym efekcie, który jest efektem losowanie kart to powinno nie być żadnej wizualizacji, ale wykonuje się wizualizacja damage. 

To rozwiązanie sprawia, że wykonują się wszystkie wizualizacje efektów naraz za każdym razem

2021-11-28 14:46 UTC, Michal-Czekanski commented on WMIAdventure/frontend/src/js/components/battle/organisms/BattleView/BattleView.js
> +
Kurde źle zaznaczyłem kod, sorry, chodziło mi o funkcję `visualizeEffects`

2021-11-28 17:27 UTC, Michal-Czekanski approved these changes
Teraz działa git, fajnie, że jest ten komponent `EffectFrame` co ogarnie od razu pare innych efektów

2021-11-28 21:23 UTC, emkarcinos commented on WMIAdventure/frontend/src/js/components/battle/organisms/BattleView/BattleView.js
> +    }
Do czego ta funkcja ma służyć? Mamy `battle.currentTurn.advance();` który zwraca wykonany w tym czasie efekt

2021-11-28 21:24 UTC, emkarcinos commented on WMIAdventure/frontend/src/js/components/battle/organisms/BattleView/BattleView.js
> +        this.visualizeEffects(effects);
Zostawiłem nawet komentarz gdzie powinno się to wykonywać. Tutaj wywołują się wszystke efekty i to nie sprawdza w ogóle jaki efekt się wykonuje w danej chwili. W `effectIconCastEffect` jest komentarz i tam powinno się wykonywać wizualizowanie efektów

2021-11-28 21:25 UTC, emkarcinos requested changes
W złym miejscu jest wykonywanie animacji tych efektów zrobione

2021-11-29 20:55 UTC, Michal-Czekanski approved these changes

2021-11-29 22:12 UTC, emkarcinos approved these changes

2021-11-29 22:12 UTC, merged