Wizualizacja efektu blokowania karty
emkarcinos/WMIAdventure pull request #684
Opened 2021-11-28 21:48 UTC by Michal-Czekanski

Closes #679 

![image](https://user-images.githubusercontent.com/43492764/143787286-8b496a2f-aa8c-4133-96d8-66c9bdce89a8.png)

Mini karty też się tak samo zachowują, jeśli np. jakaś karta była zablokowana a potem była randomizacja decka

2021-11-28 21:51 UTC, emkarcinos commented
Efekt wygląda git, podoba mi się

2021-11-28 22:53 UTC, Michal-Czekanski commented
a co sądzicie o tym, żeby pełny widok zablokowanej karty też był taki "wyszarzony"?

2021-11-28 22:55 UTC, emkarcinos commented
> a co sądzicie o tym, żeby pełny widok zablokowanej karty też był taki "wyszarzony"?

Może być za mało widoczny, ale to najłatwiejsze rozwiązanie tak myślę. Widziałbym najbardziej żeby była czarnobiała, ale to pewnie ciężko by zrobić

2021-11-28 23:06 UTC, Michal-Czekanski commented
> > a co sądzicie o tym, żeby pełny widok zablokowanej karty też był taki "wyszarzony"?
> 
> Może być za mało widoczny, ale to najłatwiejsze rozwiązanie tak myślę. Widziałbym najbardziej żeby była czarnobiała, ale to pewnie ciężko by zrobić

to może zostawię bez tego wyszarzania, widać że karta jest zablokowana w decku

2021-11-29 14:25 UTC, emkarcinos requested changes
- Zablokowana karta dalej wykonuje swoje efekty?
- Na mobilce działa tak jak trzeba, natomiast na desktopie zatrzymana karta po wysunięciu się na środek pola pojedynku nie jest już wyszarzona
- Tak samo na desktopie nie działa ten efekt poprawnie jeżeli kolejność kart zmieni się zanim zablokowana karta się wykona. Zrobiłem kartę która blokuję działanie następnej karty i zamienia losowo kolejność kart. Na mobilce działa OK, na desktopie karta przestaje być wyszarzona
- Mobile - jeżeli zablokowana karta trafi na inne miejsce w decku to widzimy, że jest wyszarzona. W kolejnych turach karta przesuwa się dalej i cały czas jest wyszarzona, czyli wszysko jest OK. Natomiast jak karta trafi już na samą górę w decku, to przestaje być wyszarzona

2021-11-29 22:34 UTC, emkarcinos commented
Rebase na `main`

2021-11-29 22:59 UTC, emkarcinos approved these changes

2021-11-29 22:59 UTC, merged