Implementacja nowego navbara
emkarcinos/WMIAdventure pull request #717
Opened 2021-12-01 17:42 UTC by emkarcinos

Closes #341 
Zrobiony navbar na desktopie i mobilce.

Zróbcie dobry CR, bo to mój pierwszy implementacyjny task HTML/CSS.

Ciężko teraz się wszędzie podostawać jak nie ma tego menu, ale chyba znacie adresy podstron żeby potestować

2021-12-01 18:48 UTC, Michal-Czekanski requested changes
Na głownej stronce na mobilce powinno być `WMI`
![image](https://user-images.githubusercontent.com/43492764/144295112-94380f56-f941-408f-bdf3-b613f813a952.png)

Teraz też jak klikniemy w button `<` to mamy error
![image](https://user-images.githubusercontent.com/43492764/144295240-71ea74bf-3877-4ad1-8e01-0d771063adf1.png)

2021-12-01 18:53 UTC, mattyl006 requested changes
Jedyny taki html'owy błąd to to co napisałem w review.
Inne sugestie:
1. Wywaliłbym stary navbar z /adventure i /ranking. Usunął w ogóle ten prototypowy komponent navbarowy
2. Jeżeli chcemy mieć później ładne przejście tego przycisku do menu na krzyżyk, to można zrobić tego hamburgera za pomocą css zamiast grafiki svg, tak jak np. tu https://www.youtube.com/watch?v=dIyVTjJAkLw ale nie jest to konieczne

2021-12-01 18:53 UTC, mattyl006 commented on WMIAdventure/frontend/src/js/components/global/molecules/Navbar/Navbar.js
> +                    </Link>
Tu bym zrobił jednym elementem jako link, tak jak jest Back zrobione, nie jako button w linku. Według walidatora to jest zła praktyka. 
![image](https://user-images.githubusercontent.com/51495505/144294552-6cab610e-c6a3-4211-8ad2-51553422a7da.png)

2021-12-01 18:55 UTC, mattyl006 commented
> Na głownej stronce na mobilce powinno być `WMI` ![image](https://user-images.githubusercontent.com/43492764/144295112-94380f56-f941-408f-bdf3-b613f813a952.png)
> 
> Teraz też jak klikniemy w button `<` to mamy error ![image](https://user-images.githubusercontent.com/43492764/144295240-71ea74bf-3877-4ad1-8e01-0d771063adf1.png)

a to ciekawe, bo u mnie tak nie jest xd
ale no, lepiej by było z Wmi raczej

2021-12-01 19:24 UTC, mattyl006 commented
A i jeszcze zastanawiam się dlaczego NavBar jako molekuła, jeśli nie będzie w nim żadnych podkomponentów, to może być jako atom. Ten prototypowy był molekułą bo w nim były pomniejsze komponenty, a tutaj mamy tylko ten NavBar ze styled-components, który raczej nie będzie miał nic więcej w sobie

2021-12-02 19:26 UTC, Michal-Czekanski approved these changes
Wiem, że czekasz na wysuwane menu ale navbar dla mnie już git

2021-12-02 20:27 UTC, mattyl006 approved these changes
Dla mnie też navbar już gites

2021-12-03 05:48 UTC, merged