#704 Added desktop variant for Navmenu
emkarcinos/WMIAdventure pull request #723
Opened 2021-12-03 21:54 UTC by emkarcinos

Zdecydowałem się nie robić tego tak jak na Figmie, że menu wysuwa się przy hoverze i jest na środku ekranu. Na poprzedniej wersji navbara to działało dobrze, bo przycisk nie był z boku ekranu. Teraz jest to niepotrzebne i psuje to flow.

2021-12-03 23:13 UTC, mattyl006 requested changes
Nie podoba mi się to, że po kliknięciu w hamburger button, ten krzyżyk do zamykania menu jest w innym miejscu.
Źle to wpływa na UX.
Powinien być w tym samym miejscu, tak abyś mógł szybko otworzyć i zamknąć klikając dwa razy bez przesunięcia myszy.

Dotyczy to mobile i desktop.

2021-12-03 23:14 UTC, mattyl006 commented
Dodałbym jeszcze jakiś efekt na hover przy linkach. Aby zmieniły kolor na przykład.

2021-12-03 23:28 UTC, emkarcinos commented
Dodałem powiększanie się itemów na hoverze i zrobiłem ten przycisk zamykania wg tego co mówiłeś

2021-12-03 23:42 UTC, mattyl006 commented
1. Jeszcze mi się przypomniało, aby zmienić "Zgłoś błąd" na "Zgłoś sugestię" czy coś takiego, aby było bardziej ogólne tak jak nasz promotor mówił
2. Dodałbym jeszcze opcję "Mój profil" aby z tego menu dało się wejść

2021-12-03 23:52 UTC, mattyl006 requested changes
to co wyżej napisałem

2021-12-03 23:53 UTC, mattyl006 commented
Nie otwierałbym menu przy hoverze, to dziwne

2021-12-03 23:53 UTC, emkarcinos commented
"Mój profil" będzie jak klikniemy w nasz profil na dole.

Zmieniłem ten tekst i dodałem że na desktopie menubar wysuwa się jak zrobimy hover

2021-12-04 09:12 UTC, mattyl006 requested changes
Spoko jest, tylko dodaj jeszcze aby link do profilu w menu, przenosił do tej podstrony z profilem

2021-12-04 09:17 UTC, mattyl006 commented
Wykryłem jeszcze jeden błąd, w podstronie http://localhost/cards-creator-start nie działa zaciemnienie tła, oraz wyjście z menu gdy klikniemy poza nim

2021-12-04 09:20 UTC, mattyl006 commented
Ogólnie to przypomniałem sobie że jest w global/organisms gotowy komponent na to zaciemnione tło, bo to był strasznie powtarzalny się case.

2021-12-04 09:26 UTC, mattyl006 commented
I teraz, jak komponent Menubar jest w Navbar, to Navbar powinien być molekułą, a Menubar atomem

2021-12-04 09:29 UTC, mattyl006 commented
`import TransparentBack from "../../../prototype/atoms/NavMenu/styled-components/TransparentBack";`

Importujesz coś takiego w Menubar. Tak nie powinno być, jak już robimy coś aktualnego, to w ogóle z tych prototypowych rzeczy nie powinniśmy korzystać, tylko je wywalić. Możesz te TransparentBack po prostu przenieść do styled components MenuBar, jeśli będzie za dużo zachodu z refactorem tak aby reużywać tego gotowego TransBack w globalsach.

2021-12-04 10:55 UTC, mattyl006 approved these changes

2021-12-04 12:09 UTC, Michal-Czekanski approved these changes

2021-12-04 12:16 UTC, merged