Implementacja designu edytora decku mobile
emkarcinos/WMIAdventure pull request #775
Opened 2021-12-08 20:28 UTC by emkarcinos

Na razie jest tylko w profilu użytkownika na mobilce. Kliknijcie na kartę dowolną to wyświetli się popup

2021-12-09 11:56 UTC, mattyl006 requested changes
Test fail:

1. Klikam w dowolną kartę w talii
2. Widzę jej pozycję w decku
3. Przestawiam widoki po innych kartach za pomocą przycisków pod "wyszukaj"
4. Przestawiając widoki pozycja w decku nie zmienia się w zależności znajdowania się w danym widoku karty

2021-12-09 12:01 UTC, mattyl006 commented
Chyba test fail, ale nie jestem pewien:
1. Przestawianie pozycji w decku wydaje się że działa
2. Jednak po odświerzeniu deck jest w pierwotnych pozycjach

Czy tak ma narazie być? Backend nie był synchronizowany?

2021-12-09 12:21 UTC, emkarcinos commented
> Chyba test fail, ale nie jestem pewien:
> 
> 1. Przestawianie pozycji w decku wydaje się że działa
> 2. Jednak po odświerzeniu deck jest w pierwotnych pozycjach
> 
> Czy tak ma narazie być? Backend nie był synchronizowany?

Jeszcze backendu nie podpinałem, mogłem w sumie napisać w PR, sorry

2021-12-09 17:18 UTC, mattyl006 commented
To doszliśmy w końcu do tego, że te karty które są w decku powinny być wyszarzone i wyświetlać alert już po kliknięciu.

2021-12-09 19:16 UTC, Michal-Czekanski requested changes
#### Na desktopie popup edycji u mnie nie działa jak trzeba:
![image](https://user-images.githubusercontent.com/43492764/145460134-c605b3a0-a6c1-46e2-9f26-6d5d401360a5.png)

![image](https://user-images.githubusercontent.com/43492764/145460190-532386ac-52f9-4897-a5b9-4c854b86e694.png)

Też przydałaby się zmiana kursora po najeżdżaniu myszką na kartę, bo nic nie wskazuje, że można tu kliknąć (może też jakiś tekścik "Kliknij na kartę, by edytować"?)

#### Na firefox nie widzę poprawnie pozycji w talii
##### Mobilka
![image](https://user-images.githubusercontent.com/43492764/145460451-5bbce3de-231b-476b-8b2e-0014e1627639.png)

##### Desktop
![image](https://user-images.githubusercontent.com/43492764/145460548-4689dacb-2c22-4445-8f06-42018c30efef.png)

2021-12-09 19:47 UTC, mattyl006 approved these changes
Nie widzę nic do poprawy

2021-12-10 06:47 UTC, Michal-Czekanski approved these changes
Jestem dzbanem xD

2021-12-10 06:48 UTC, merged