Edytor talii desktop
emkarcinos/WMIAdventure pull request #785
Opened 2021-12-10 19:52 UTC by emkarcinos

Closes #748

2021-12-10 21:25 UTC, Michal-Czekanski requested changes
To jest piękne, że tylko 4 pliki się zmieniły xD

### Przydały by się takie rzeczy:

#### ~~Zmiana kursora po najechaniu myszką na kartę~~ (nie zauważyłem, że w innym PR zrobiłeś)

#### Na firefox słabo widać przez strzałki jaką ma kolejność w talii dana karta
![image](https://user-images.githubusercontent.com/43492764/145641946-0e01839a-9cc2-4590-89bf-ece31e398d1f.png)

#### Przy zmianie pozycji w talii danej karty reszta kart zachowuje się w dość niespodziewany sposób:
- Mamy kartę na pozycji 3 `Przykład 5` oraz deck w stanie jak na skrinie:
![image](https://user-images.githubusercontent.com/43492764/145642098-591dcab2-fd8c-4646-9278-08c2f3e37439.png)
- Dajemy jej pozycję w talii 1 i oczekiwany efekt moim zdaniem to zamiana miejsc z kartą `TEST_CARD1`, ale dzieje się coś takiego:
![image](https://user-images.githubusercontent.com/43492764/145642557-af55a4e7-f9ca-4435-9266-151080a5366a.png)

Karta `Przykład 5` wskoczyła na swoje miejsce, ale zamiast zamienić się miejscami z `TEST_CARD1` to przesunęła resztę kart w prawo.

Przez to układanie talii jest utrudnione, bo nam przesuwa inne karty, które mamy na określonych miejscach

#### Pomimo błędu od serwera i wyskoczenia komunikatu, że nie udało się zaktualizować talii, aktualizuje się ona

![image](https://user-images.githubusercontent.com/43492764/145643216-bffd19d1-355c-4f18-8158-6c718940c1c1.png)
![image](https://user-images.githubusercontent.com/43492764/145643258-b1f7d7aa-5cc9-4820-884e-0b66e56e0f47.png)

2021-12-11 09:53 UTC, mattyl006 reviewed
`ChangeDeckCard.js` dałbym jako organizm

2021-12-11 10:04 UTC, Michal-Czekanski approved these changes
Git

2021-12-11 11:13 UTC, mattyl006 requested changes
Ten podpis pod kartami był fajny, a teraz go u mnie nie widzę.

![image](https://user-images.githubusercontent.com/51495505/145674430-045c2feb-5ba7-4ab1-b1bf-7e37d4ce47ce.png)

2021-12-11 11:29 UTC, mattyl006 commented
Jak przestawiłem pozycję karty to opis znikł
![image](https://user-images.githubusercontent.com/51495505/145674822-0ab60992-5e38-43c0-b876-ebc6ead795d7.png)

2021-12-11 11:30 UTC, mattyl006 commented
Gdy najeżdżam myszką na jakąś kartę, to przydałby się `cursor: pointer` plus jakaś animacja scale

2021-12-11 14:04 UTC, mattyl006 approved these changes

2021-12-11 14:15 UTC, mattyl006 requested changes
Znalazłem jeszcze na mobile, że pop upy nakładają się na siebie w taki sposób
![image](https://user-images.githubusercontent.com/51495505/145679737-1a4d4782-b863-4aec-8306-db9127ba41b3.png)

Tryb battle -> Tiny profile -> Edycja talii

2021-12-11 15:27 UTC, mattyl006 approved these changes

2021-12-11 15:28 UTC, merged