Redirecty
emkarcinos/WMIAdventure pull request #837
Opened 2021-12-17 21:28 UTC by emkarcinos

Closes #819

Jak jesteśmy już zalogowani to mamy dostęp do wszystkich widoków poza:
- Landing Page
- Login
- Register

Jak nie jesteśmy zalgoowani, to mamy dostęp tylko do widoków wymienionych wyżej, próba wejścia np w Battle zredirectuje nas na Landing Page.

Przy logowaniu, rejestracji, wylogowywaniu musiałem zrobić `window.location.reload()`, żeby zmusić state apki do aktualizacji, żeby router dostał kopa.

2021-12-17 22:38 UTC, mattyl006 requested changes
Jestem zalogowany.
Klikam "Strona główna" w nav menu i mamy white screen.

Trzeba zmienić tam link z '/' na '/main'

2021-12-17 23:14 UTC, emkarcinos commented
Poprawiłem to w taki sposób, że nie wyświetlamy w ogóle tych przycisków w Menubarze

2021-12-18 01:30 UTC, Michal-Czekanski reviewed
Klikam pare razy w tux'a i mam error 
![image](https://user-images.githubusercontent.com/43492764/146624495-0b126860-681c-44ba-9b80-2d120246b026.png)
![image](https://user-images.githubusercontent.com/43492764/146624504-bf39f38c-0320-4292-80f2-fe231a1677e6.png)

2021-12-18 01:33 UTC, Michal-Czekanski commented
- Na mobilce będąc zalogowanym jestem na main menu 
- wchodzę w battle
- klikam strzałkę "cofnij" w lewym górnym rogu
- nie cofa mnie na `/main` tylko na `/` i mam biały ekran

2021-12-18 08:18 UTC, mattyl006 commented
Pamiętam, że @emkarcinos miałeś problem z tym cofaniem. Próbowałeś może wywoływać po prostu przeglądarkowe "wstecz"?. Da się wywołać refresh, więc wstecz pewnie też można.

2021-12-18 08:19 UTC, emkarcinos commented
Właśnie chyba tak zrobię, tylko problem pokawia się jak wstecz nas zabierze na inną stronkę

2021-12-18 08:22 UTC, mattyl006 commented
Aa no tak, tutaj trzeba coś wykombinować. Ale kurde, na pewno to jest częsty case, pewnie są na to jakieś tutoriale czy coś xd

2021-12-18 08:59 UTC, emkarcinos commented
W Reactcie to jest najczęściej implementowane w `App` gdzie jest cały `Router`. Wrzucasz tam navbara i potem nie musisz martwić się o niego już w komponentach. Sam Navbar też wtedy jest komponentem routerowym i on ma jakiś dostęp do tej reactowej historii, mogę spróbować to zrobić aczkolwiek właśnie dlatego zastanawiałem się dlaczego zrobiłeś osobnego navbara, bo to trochę komplikuje sprawę jakbym chciał to tak zrobić. Plus psują się wysokości wszystkich widoków potem, content wchodzi za navbar, itp

2021-12-18 09:04 UTC, mattyl006 commented
No nie pomyślałem o tym po prostu. Wyklepałem w 5min tego landing nav bara, bo mi było tak wygodniej i szybciej niż korzystać z tego normalnego, bo tam bym musiał przerabiać, ukrywać rzeczy itd.

Można przerobić ten LandingNavBar aby był tym NavBar, jeśli tak będzie najprościej. Mogę to zrobić w osobnym tasku czy coś.

2021-12-18 09:05 UTC, emkarcinos commented
Zobaczę w takim razie ile czasu mi to zajmie.
Ja też jak robiłem głównego navbara to zrobiłem to po chuju, bo nie wiedziałem ze tak można

2021-12-18 13:18 UTC, mattyl006 approved these changes
u mnie działa git

2021-12-18 13:21 UTC, merged