Ukrycie prototypowego kontentu
emkarcinos/WMIAdventure pull request #856
Opened 2021-12-20 20:58 UTC by mattyl006

closes #804

2021-12-20 21:30 UTC, Michal-Czekanski reviewed
ukryłbym też semestry

2021-12-20 21:49 UTC, Michal-Czekanski approved these changes

2021-12-21 09:07 UTC, emkarcinos requested changes
Jeszcze trzeba usunąć wygrane / przegrane z profile view

2021-12-21 13:04 UTC, emkarcinos approved these changes

2021-12-21 13:04 UTC, merged